// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tewycvxjuzamkdcflxzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRld3ljdnhqdXphbWtkY2ZseHprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNzA2MzAsImV4cCI6MjA2ODg0NjYzMH0.Px_ECB8zVXAhYaTDhLQ6BlJQcQWmc6iMQ51je-Csjto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});